Sawmill/Controllers/TargetAppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plywood.Sawmill.Models;

namespace Plywood.Sawmill.Controllers
{
    [Authorize]
    public class TargetAppsController : Controller
    {
        //
        // GET: /TargetApps/

        public ActionResult Index(Guid tid, string q = null, int o = 0, int c = 50)
        {
            var targetApps = new TargetApps();
            var targets = new Targets();
            var groups = new Groups();

            var targetAppList = targetApps.SearchTargetApps(tid, q, o, c);
            var target = targets.GetTarget(tid);
            var group = groups.GetGroup(target.GroupKey);

            var model = new TargetAppsIndex()
            {
                TargetAppList = targetAppList,
                Target = target,
                Group = group,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddApp(Guid tid, Guid aid)
        {
            var targetApps = new TargetApps();
            targetApps.AddApp(tid, aid);
            return RedirectToAction("Index", new { tid = tid });
        }

        [HttpPost]
        public ActionResult RemoveApp(Guid tid, Guid aid)
        {
            var targetApps = new TargetApps();
            targetApps.RemoveApp(tid, aid);
            return RedirectToAction("Index", new { tid = tid });
        }

        public ActionResult Version(Guid tid, Guid aid)
        {
            var targetAppVersions = new TargetAppVersions();
            var versions = new Versions();
            var apps = new Apps();
            var targets = new Targets();
            var groups = new Groups();

            Version version;
            var versionKey = targetAppVersions.GetTargetAppVersion(tid, aid);
            if (versionKey.HasValue)
            {
                try
                {
                    version = versions.GetVersion(versionKey.Value);
                }
                catch (Exception)
                {
                    version = null;
                }
            }
            else
            {
                version = null;
            }

            var app = apps.GetApp(aid);
            var target = targets.GetTarget(tid);
            var group = groups.GetGroup(target.GroupKey);

            var model = new TargetAppVersionDetails()
            {
                Version = version,
                App = app,
                Target = target,
                Group = group,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangeVersion(Guid tid, Guid aid, Guid vid)
        {
            var targetAppVersions = new TargetAppVersions();
            targetAppVersions.SetTargetAppVersion(tid, aid, vid);
            return RedirectToAction("Version", new { tid = tid, aid = aid });
        }

        [HttpPost]
        public ActionResult RemoveVersion(Guid tid, Guid aid)
        {
            var targetAppVersions = new TargetAppVersions();
            targetAppVersions.SetTargetAppVersion(tid, aid, null);
            return RedirectToAction("Version", new { tid = tid, aid = aid });
        }
    }
}

Sawmill/Controllers/VersionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Plywood.Sawmill.Models;

namespace Plywood.Sawmill.Controllers
{
    [Authorize]
    public class VersionsController : Controller
    {
        //
        // GET: /Versions/

        public ActionResult Index(Guid aid, string q = null, DateTime? f = null, DateTime? t = null, int o = 0, int c = 50)
        {
            if (o < 0) o = 0;
            if (c < 1) o = 1;
            if (c > 100) o = 100;

            var versions = new Versions();
            var apps = new Apps();
            var groups = new Groups();

            var versionList = versions.SearchAppVersions(aid, f, t, q, o, c);
            var app = apps.GetApp(aid);
            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionIndex()
            {
                VersionList = versionList,
                App = app,
                Group = group,
            };
            return View(model);
        }

        public ActionResult Autocomplete(Guid aid, string query, int offset = 0, int count = 10)
        {
            var versions = new Versions();
            var versionList = versions.SearchAppVersions(aid, null, null, query, offset, count);
            return Json(versionList);
        }

        public ActionResult Details(Guid id)
        {
            var versions = new Versions();
            var apps = new Apps();
            var groups = new Groups();

            var version = versions.GetVersion(id);
            var app = apps.GetApp(version.AppKey);
            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };
            return View(model);
        }

        public ActionResult Create(Guid aid)
        {
            var apps = new Apps();
            var groups = new Groups();

            var app = apps.GetApp(aid);
            var group = groups.GetGroup(app.GroupKey);
            var version = new Version()
            {
                AppKey = aid,
                GroupKey = group.Key,
                VersionNumber = string.Format("{0}.{1}", app.MajorVersion, app.Revision)
            };

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Guid aid, string comment, DateTime timestamp)
        {
            var apps = new Apps();
            var app = apps.GetApp(aid);

            var newVersion = new Version()
            {
                AppKey = aid,
                Comment = comment,
                Timestamp = timestamp,
                VersionNumber = string.Format("{0}.{1}", app.MajorVersion, app.Revision),
            };

            if (string.IsNullOrWhiteSpace(comment)) ModelState.AddModelError("comment", "Comment is required.");

            if (ModelState.IsValid)
            {
                try
                {
                    var versions = new Versions();
                    versions.CreateVersion(newVersion);

                    app.Revision += 1;
                    apps.UpdateApp(app);

                    return RedirectToAction("Details", new { id = newVersion.Key });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Error", ex);
                }
            }

            var groups = new Groups();

            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionDetails()
            {
                Version = newVersion,
                App = app,
                Group = group,
            };

            return View(model);
        }

        public ActionResult ConfirmDelete(Guid id)
        {
            var versions = new Versions();
            var apps = new Apps();
            var groups = new Groups();

            var version = versions.GetVersion(id);
            var app = apps.GetApp(version.AppKey);
            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var versions = new Versions();
            var version = versions.GetVersion(id);

            try
            {
                versions.DeleteVersion(id);
                return RedirectToAction("Index", new { aid = version.AppKey });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);

                var apps = new Apps();
                var app = apps.GetApp(version.AppKey);

                var groups = new Groups();
                var group = groups.GetGroup(version.GroupKey);

                var model = new VersionDetails()
                {
                    Version = version,
                    App = app,
                    Group = group,
                };

                return View("ConfirmDelete", model);
            }
        }

        public ActionResult Edit(Guid id)
        {
            var versions = new Versions();
            var apps = new Apps();
            var groups = new Groups();

            var version = versions.GetVersion(id);
            var app = apps.GetApp(version.AppKey);
            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Guid id, string comment)
        {
            Version version = null;
            try
            {
                var versions = new Versions();
                version = versions.GetVersion(id);
                version.Comment = comment;
                versions.UpdateVersion(version);
                return RedirectToAction("Details", new { id = version.Key });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex);
            }

            var groups = new Groups();
            var apps = new Apps();
            Group group = null;
            App app = null;
            if (version != null)
            {
                group = groups.GetGroup(version.GroupKey);
                app = apps.GetApp(version.AppKey);
            }

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };

            return View(model);
        }

        public ActionResult EditTags(Guid id)
        {
            var versions = new Versions();
            var apps = new Apps();
            var groups = new Groups();

            var version = versions.GetVersion(id);
            var app = apps.GetApp(version.AppKey);
            var group = groups.GetGroup(app.GroupKey);

            var model = new VersionDetails()
            {
                Version = version,
                App = app,
                Group = group,
            };
            return View(model);
        }

        [HttpPost]
        public JsonResult RemoveTag(Guid id, string name)
        {
            var versions = new Versions();
            var version = versions.GetVersion(id);
            if (!version.Tags.ContainsKey(name))
                throw new HttpException(404, "Tag not found");

            version.Tags.Remove(name);
            versions.UpdateVersion(version);
            return Json(null);
        }

        [HttpPost]
        public ActionResult AddTag(Guid id, string name, string value)
        {
            var versions = new Versions();
            var version = versions.GetVersion(id);
            if (version.Tags.ContainsKey(name))
                throw new HttpException(406, "Tag name already exists");

            version.Tags.Add(name, value);
            versions.UpdateVersion(version);
            if (Request.IsAjaxRequest())
                return Json(null);
            else
                return RedirectToAction("EditTags", new { id = id });
        }

        [HttpPost]
        public JsonResult UpdateTag(Guid id, string oldName, string name, string value)
        {
            var versions = new Versions();
            var version = versions.GetVersion(id);
            if (!version.Tags.ContainsKey(oldName))
                throw new HttpException(404, "Tag not found");

            if (oldName == name)
            {
                version.Tags[name] = value;
            }
            else if (version.Tags.ContainsKey(name))
            {
                throw new HttpException(406, "Tag name already exists");
            }
            else
            {
                version.Tags.Remove(oldName);
                version.Tags.Add(name, value);
            }
            versions.UpdateVersion(version);
            return Json(null);
        }
    }
}

Sawmill/Views/TargetApps/Index.cshtml
@model Plywood.Sawmill.Models.TargetAppsIndex
@{
  ViewBag.Title = Model.Target.Name + " Apps";
}
<div class="pagesizer">
  @Html.PageSizeSwitcher(Url.Action("Index"), Model.TargetAppList.PageSize, new int[] { 10, 25, 50 })
</div>
<div class="breadcrumbs">
  @Html.ActionLink("Groups", "Index", "Groups")
  >
  @Html.ActionLink(Model.Group.Name, "Details", "Groups", new { id = Model.Group.Key }, null)
  >
  @Html.ActionLink("Targets", "Index", "Targets", new { gid = Model.Group.Key }, null)
  >
  @Html.ActionLink(Model.Target.Name, "Details", "Targets", new { id = Model.Target.Key }, null)
  > Apps
</div>
<ul class="page-tabs">
  <li>@Html.ActionLink("Target Details", "Details", "Targets", new { id = Model.Target.Key }, null)</li>
  <li class="selected">@Html.ActionLink("Apps", "Index", "TargetApps", new { tid = Model.Target.Key }, null)</li>
  <li>@Html.ActionLink("Instances", "Index", "Instances", new { tid = Model.Target.Key }, null)</li>
</ul>
<div class="page-tab-content">
  <div class="paging">
    @Html.NextPrevPager(Url.Action("Index"), Model.TargetAppList.PageSize, Model.TargetAppList.Offset, Model.TargetAppList.TotalCount)
  </div>
  <table>
    <tr>
      <th>
        Name
      </th>
      <th>
      </th>
      <th>
      </th>
    </tr>
    @foreach (var app in Model.TargetAppList.Apps)
    {
      <tr>
        <td>
          @Html.ActionLink(app.Name, "Details", "Apps", new { id = app.Key }, null)
        </td>
        <td>
          @Html.ActionLink("Deployed Version", "Version", "TargetApps", new { tid = Model.Target.Key, aid = app.Key }, null)
        </td>
        <td>
          @using (Html.BeginForm("RemoveApp", "TargetApps", FormMethod.Post))
          {
            <div>
              <input type="hidden" name="tid" value="@Model.Target.Key" />
              <input type="hidden" name="aid" value="@app.Key" />
              <input type="submit" value="Remove" />
            </div>
          }
        </td>
      </tr>
    }
  </table>
  <div class="paging">
    @Html.NextPrevPager(Url.Action("Index"), Model.TargetAppList.PageSize, Model.TargetAppList.Offset, Model.TargetAppList.TotalCount)
  </div>
</div>
<script type="text/javascript">
  $(function () {
    var autocompleteSource;
    $('#app-name-search').autocomplete({
      source: function (req, res) {
        $.ajax({
          url: '@Url.Action("Autocomplete", "Apps")',
          dataType: "json",
          type: "POST",
          data: {
            gid: '@Model.Group.Key',
            query: req.term
          },
          success: function (data) {
            autocompleteSource = data.Apps;
            res($.map(data.Apps, function (item) {
              return {
                label: item.Name,
                value: item.Key
              };
            }));
          }
        });
      },
      minLength: 3,
      select: function (event, ui) {
        $('#app-name-search').val(ui.item.label);
        $('#app-id').val(ui.item.value);
        return false;
      }
    });
  });
</script>
@using (Html.BeginForm("AddApp", "TargetApps", FormMethod.Post))
{
  <fieldset>
    <legend>Add App</legend>
    <input name="tid" type="hidden" value="@Model.Target.Key" />
    <input id="app-id" type="hidden" name="aid" />
    <label for="app-name-search">
      App Name</label>
    <input id="app-name-search" type="text" value="" />
    <input type="submit" value="Add App" />
  </fieldset>
}

Sawmill/Views/TargetApps/Version.cshtml
@model Plywood.Sawmill.Models.TargetAppVersionDetails
@{
  ViewBag.Title = Model.Target.Name + " - " + Model.App.Name + " - Deployed Version";
}
<div class="breadcrumbs">
  @Html.ActionLink("Groups", "Index", "Groups")
  >
  @Html.ActionLink(Model.Group.Name, "Details", "Groups", new { id = Model.Group.Key }, null)
  >
  @Html.ActionLink("Targets", "Index", "Targets", new { gid = Model.Group.Key }, null)
  >
  @Html.ActionLink(Model.Target.Name, "Details", "Targets", new { id = Model.Target.Key }, null)
  >
  @Html.ActionLink("Apps", "Index", "TargetApps", new { tid = Model.Target.Key }, null)
  >
  @Model.App.Name
  - Deployed Version
</div>
<fieldset>
  <legend>Deployed Version</legend>
  @if (Model.Version != null)
  {
    <div class="display-label">
      Key
    </div>
    <div class="display-field">
      @Model.Version.Key
    </div>
    <div class="display-label">
      Date
    </div>
    <div class="display-field">
      @Model.Version.Timestamp
    </div>
    <div class="display-label">
      Name
    </div>
    <div class="display-field">
      @Html.ActionLink(Model.Version.Name, "Details", "Versions", new { id = Model.Version.Key }, null)
    </div>
  }
  else
  {
    <div>
      No version set.</div>
  }
</fieldset>
<fieldset>
  <legend>Change Deployed Version</legend>
  @using (Html.BeginForm("ChangeVersion", "TargetApps", FormMethod.Post))
  {
    <input type="hidden" name="tid" value="@Model.Target.Key" />
    <input type="hidden" name="aid" value="@Model.App.Key" />
    <input id="version-key" type="hidden" name="vid" />
    <label for="version-name-search">
      Version</label>
    <input id="version-name-search" type="text" />
    <input type="submit" value="Change" />
  }
  @using (Html.BeginForm("RemoveVersion", "TargetApps", FormMethod.Post))
  {
    <input type="hidden" name="tid" value="@Model.Target.Key" />
    <input type="hidden" name="aid" value="@Model.App.Key" />
    <input type="submit" value="Remove Deployed Version" />
  }
</fieldset>
<script type="text/javascript">
  $(function () {
    var autocompleteSource;
    $('#version-name-search').autocomplete({
      source: function (req, res) {
        $.ajax({
          url: '@Url.Action("Autocomplete", "Versions")',
          dataType: "json",
          type: "POST",
          data: {
            aid: '@Model.App.Key',
            query: req.term
          },
          success: function (data) {
            autocompleteSource = data.Versions;
            res($.map(data.Versions, function (item) {
              return {
                label: item.Name,
                value: item.Key
              };
            }));
          }
        });
      },
      minLength: 0,
      select: function (event, ui) {
        $('#version-name-search').val(ui.item.label);
        $('#version-key').val(ui.item.value);
        return false;
      }
    });
  });
</script>